image: mattfalkner/coffeebot:latest

stages:
  - test

tests:
  stage: test
  script:
    - echo "Configuring Environment"
    - npm cache clean --force
    - npm install
    - npm run setup
    - npm run tests

test-coverage:
  stage: test
  script:
    - echo "Configuring Environment"
    - npm cache clean --force
    - npm install
    - npm run setup
    - npm run coverage
  artifacts:
    paths:
      - coverage/
