image: mattfalkner/coffeebot:latest

stages:
  - test

chai-test-endpoints:
    stage: test
    script:
      - echo "Configuring Environment"
      - npm cache clean --force
      - npm install
      - npm run setup
      - npm run tests

chai-test-coverage: 
    stage: test
    script: 
      - echo "Configuring Environment"
      - npm cache clean --force
      - npm install
      - npm run setup
      - npm run coverage
