image: mattfalkner/coffeebot:latest

stages:
  - lint
  - test

eslint:
  stage: lint
  allow_failure: true
  script:
    - npm i eslint eslint-config-airbnb
    - npx install-peerdeps eslint-config-airbnb
    - npm run lint

tests:
  stage: test
  script:
    - echo "Configuring Environment"
    - npm cache clean --force
    - npm install
    - npm run setup
    - npm run tests

test-coverage:
  stage: test
  script:
    - echo "Configuring Environment"
    - npm cache clean --force
    - npm install
    - npm run setup
    - npm run coverage
  artifacts:
    paths:
      - coverage/
